### ISSUE TITLE
Initial values for the registration form are wrong

### ISSUE THREAD

**Issue by MontealegreLuis** [AceAdlister/adlister#17]
* Registration form should not show `null` 
* Password elements should not be pre-populated
* Move the Java code from the JSP to the Servlet where it belongs

**Comment by chasehammock** [comment]
Resolved this issue and the form is blank by default as it should be AND the items are sticky.

**Comment by CodeOfErikHansen** [comment]
Initial values for the registration form is fixed. Closing because it is the last day of adlister.
